### ISSUE TITLE
mpvue 框架里 引用 new wxDraw 报错

### ISSUE THREAD

**Issue by zhuangjunkun** [bobiscool/wxDraw#86]
执行：      this.wxCanvas = new wxDraw(context, 0, 0, 400, 500);
报错如下：
VM53916:1 jsEnginScriptError
Converting circular structure to JSON
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.a [as publish] (http://127.0.0.1:23391/appservice/appservice?t=1538125910377:2105:12725)
    at Object.publish (http://127.0.0.1:23391/appservice/__dev__/WAService.js:4:27046)
    at G (http://127.0.0.1:23391/appservice/__dev__/WAService.js:6:9851)
    at Object.zi [as invokeWebviewMethod] (http://127.0.0.1:23391/appservice/__dev__/WAService.js:9:22541)
    at Function.value (http://127.0.0.1:23391/appservice/__dev__/WAService.js:19:27534)
    at t.value (http://127.0.0.1:23391/appservice/__dev__/WAService.js:19:31610)
    at http://127.0.0.1:23391/appservice/vendor/js/main.js:6496:3
    at Function.later (http://127.0.0.1:23391/appservice/vendor/js/main.js:6467:19)
    at http://127.0.0.1:23391/appservice/__dev__/WAService.js:4:13561

**Comment by HAIHAI211** [comment]
我也报了同样的错误

**Comment by MohaElder** [comment]
同上
